### ISSUE TITLE
你的博客的评论系统没有正常工作

### ISSUE THREAD

**Issue by gledos** [fengyunkkx/fengyunkkx.github.io#1]
评论过区域显示这个：
>We were unable to load Disqus. If you are a moderator please see our [troubleshooting guide](https://docs.disqus.com/help/83/).

**Comment by fengyunkkx** [comment]
感谢提醒，搁置了几个月之后总算是修复了这个问题。

Disqus 被神秘力量影响，评论区已经更换为新的 Livere 插件，应该可以正常工作了
